### ISSUE TITLE
merged System B and System A and question about SystemC

### ISSUE THREAD

**Issue by darioalessandro** [darioalessandro/17655-D#33]
Hey Paul I fixed System B and adjusted ```TransformFrameFilter```

Turns out that it is not possible to use the SmoothFilter to both smooth the data and to filter out wildpoints, at least I was not able to figure it out in one shot. 

I added

```
TransformFrameFilter filterNormalPoints = new TransformFrameFilter(frame -> {
            return (frame.smoothedPressure != null) ? Optional.of(frame) : Optional.empty();
        });

```
to filter out the normal points.

I tried to run C but I get:

```
Connected filter Thread-13 - Thread-12
Connected filter Thread-11 - Thread-10
Connected outplut Thread-12 to split filter: Thread-9
Connected outplut Thread-10 to split filter: Thread-9
Connected filter Thread-9 - Thread-8
Connected filter Thread-7 - Thread-6
Connected outplut Thread-8 to split filter: Thread-5
Connected outplut Thread-6 to split filter: Thread-5
Connected filter Thread-5 - Thread-4
Connected filter Thread-4 - Thread-1
Connected filter Thread-1 - Thread-0
Connected filter Thread-3 - Thread-2

Thread-0::Source reading file...

Thread-2::Source reading file...
Exception in thread "main" 
Thread-1::BytesToFrameFilter 
Thread-3::BytesToFrameFilter java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:708)
        at SystemC.main(SystemC.java:143)

```

**Comment by PaulFenton** [comment]
I will debug system C at some point today.

Regarding the smooth point filtering, maybe I misunderstand what you're trying to do. I was originally proposing two separate instances of the smooth filter with 2 different callbacks, one on the top branch that transforms the wild points, and one on the lower logging branch that filters them.

I do have one question about the use of Optionals in the smooth filter, is it possible that line 60 of FrameSmoothFilter.java is executing ahead of line 57? Since we have a whole bunch of threads running, I'm not confident that we can expect the callback to come first... should we move the frame writing into the callback?

If we can get it working, I like the idea of using Optionals or Nulls that remove a bad frame before even writing it. In general I think passing around meta-data should be minimized... 

That being said, I looked at the case where we are using "originalPressure" and "modifiedPressure" and I couldn't find a good/easy way of eliminating the meta-data. Maybe we are at a point where we just get it working and document our thoughts on how to improve.

**Comment by darioalessandro** [comment]
I do not think that 60 is being executed before 57 because it all runs in the same thread.

I am not sure if I'll get to another pass of this particular nit, instead, I would like to focus tonight on meeting System B smooth filter goals.
